version: '3.8'
services:
  frontend:
    build:
      context: ./ui_code
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    build:
      context: ./java_code
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

